# Generated by Django 4.0.6 on 2022-07-12 00:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
