# Generated by Django 4.0.6 on 2022-07-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0003_auto_20220712_0324'),
    ]

    operations = [
    ]
