# Generated by Django 4.0.6 on 2022-07-12 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0006_alter_user_is_charity_alter_user_is_donor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
