# Generated by Django 4.0.6 on 2022-07-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0008_alter_donor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='country',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='country',
        ),
        migrations.DeleteModel(
            name='AnonymousDonation',
        ),
    ]
