# Generated by Django 4.0.6 on 2022-07-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0009_remove_beneficiary_country_remove_charity_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnonymousDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(default='Paypal', max_length=30)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donationApp.charity')),
            ],
        ),
    ]
