# Generated by Django 4.0.6 on 2022-07-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0010_tokens_anonymousdonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='charity',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='amount_raised',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='charity',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='date_donated',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='donation_frequency',
        ),
        migrations.AddField(
            model_name='donations',
            name='target_amount',
            field=models.IntegerField(choices=[(100000, '$100,000'), (200000, '$200,000'), (300000, '$300,000'), (400000, '$400,000'), (500000, '$500,000'), (700000, '$700,000'), (600000, '$600,000'), (800000, '$800,000'), (900000, '$900,000'), (1000000, '$1M+')], null=True),
        ),
        migrations.DeleteModel(
            name='AnonymousDonation',
        ),
        migrations.DeleteModel(
            name='Beneficiary',
        ),
    ]
